### ISSUE TITLE
Similar Project

### ISSUE THREAD

**Issue by zuphilip** [lunactic/kraken_docker#1]
There is a similar project: https://github.com/kba/kraken-docker by @kba . Maybe it make sense to work together with my colleague.

**Comment by lunactic** [comment]
I found that project when I did some research.
But, I decided to create my own Dockerfile because I need an image that provides me with shell access.

**Comment by zuphilip** [comment]
I am not sure I understand, but you can do something like
```
docker run kbai/kraken-docker bash
```

**Comment by kba** [comment]
As @zuphilip writes, you should be able to do that with kbai/kraken-docker. It's much the same, except that it is based on Alpine Linux/busybox so it should be really lean and small.

It doesn't include `bash` but the busybox shell which is mostly compliant except for bashisms. But if that's something you need, it's no problem to add.

```sh
docker run --rm -it kbai/kraken-docker sh
```

**Comment by lunactic** [comment]
@kba Thanks for that reply. So I it was just my error in figuring out the specific details.
I'll see if I can make things work by adapting your set-up a bit then (as I probably will need a few additional packages)

**Comment by kba** [comment]
Cool, looking forward to your adaptions and great to see @mittagessen's see a wider user base :+1:

**Comment by lunactic** [comment]
The project looks really interesting and I run into some problems using the default ocropus installation (mainly due to python libraries) so I'm looking forward to try it out.

**Comment by lunactic** [comment]
I will close this issue here and delete the repo in a couple of days.
If I figure out what I would need I create a PR and then can see if it makes sense to integrate my needs directly there or create a fork of it.

**Comment by zuphilip** [comment]
Cool, that sounds great! :+1: 

BTW the ocropus docker https://hub.docker.com/r/kbai/ocropy/ works and deals with the dependencies for you.
